version = 1.0.0
deb_dir = secspace_server_web_deb

all: builddir createdeb
	echo "OK"

builddir:
	mkdir -p $(deb_dir)/usr/local/secspace_server_web
	# cp -rf app.js lib node_modules shop.js views info.js login.js manage.js public $(deb_dir)/usr/local/secspace_server_web/
	ls |egrep -v "Makefile.builddeb|secspace_server_web_deb" | xargs -i cp -rf {} $(deb_dir)/usr/local/secspace_server_web/
createdeb:
	dpkg-deb -b $(deb_dir) secspace_server_web_$(version)_amd64_dev.deb

